sudo: false

language: node_js

node_js: "6"

cache:
  directories:
    - $HOME/.npm
    - node_modules

install:
  - npm install -g yarn
  - yarn

script:
  - npm test

after_success:
  - .travis/deploy.sh
